# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: TID
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  create_issue:
    name: Create TID issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Get current date
        id: date
        run: echo "CURRENT_DATE=$(date +%Y_%m_%d)" >> $GITHUB_ENV
      - name: Create TID issue
        uses: imjohnbo/issue-bot@3daae12aa54d38685d7ff8459fc8a2aee8cea98b
        with:
          assignees: "kimjuneseo, wnsdnn, yeongyu05, youngjoon568, pyjun01"
          labels: 'TID'
          title: ${{ env.CURRENT_DATE }}
          body: |-
            오늘 무엇을 했는지, 기능 구현하면서 어떤 문제가 있었는지를 작성합니다.
            세부적인 정보도 같이 작성합니다.
            ex)
            - 트렐로 기능 구현
              - 카드 팝업 구현
              - 드래그앤드랍 구현
            
            - 드래그앤드랍을 구현할떄 드랍한 곳의 idx를 제대로 가져오지 못했음
              - 해결: 친구가 도와줬는데 idx를 가져올때 Math 메소드를 ceil로 잘못사용하고 있었음
          pinned: false
          close-previous: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
